# Generated by Django 3.2.16 on 2022-11-16 18:07

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(upload_to=main.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), main.models.validate_image_size]),
        ),
    ]
