# Generated by Django 3.2.16 on 2022-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_request_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Комментрарий'),
        ),
    ]
