# Generated by Django 3.2.16 on 2022-11-15 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_request_starus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='photo',
            field=models.ImageField(max_length=250, upload_to='img/'),
        ),
    ]
