# Generated by Django 3.2.16 on 2022-11-15 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_request_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='starus',
            new_name='status',
        ),
    ]
