# Generated by Django 3.2.16 on 2022-11-17 05:06

import django.core.validators
from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_request_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_name_file, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg', 'bmp']), main.models.validate_image_size]),
        ),
    ]
